### ISSUE TITLE
Automated Generation of "In Office" role

### ISSUE THREAD

**Issue by BradShrewsbury** [andy3471/lunchrota#11]
**Is your feature request related to a problem? Please describe.**
I guess that the problem could be considered as the length of time it takes to manually generate all of the slots within an Excel Document before uploading the file to the website to fill in the roles. 

**Describe the solution you'd like**
The rota to automatically generate every user as "In Office" for any weekday (Mon - Fri) so that this can be edited manually by any administrator user as and where it is needed for ease of use and so that it doesn't fall on one person consistently to build the rota each month.

**Comment by andy3471** [comment]
Can be added via a daily task/command
