### ISSUE TITLE
Implementation of Crosscare 2020 R1 Password list

### ISSUE THREAD

**Issue by BradShrewsbury** [andy3471/lunchrota#62]
**Is your feature request related to a problem? Please describe.**
As of Crosscare 2020.R1, the password list is different to that of <2019.R2 in that they now contain 10 characters instead of 8.

**Describe the solution you'd like**
Upload of a secondary list so that the passwords are both available for us to access on the front end.

**Comment by andy3471** [comment]
By daily password, Is that the word list, or the number? 

I take it you'd need a switch to see both still?

**Comment by BradShrewsbury** [comment]
The word list and yes, we'd still need to see both until such a stage where all customers were moved onto the newest version.

**Comment by andy3471** [comment]
Added a password 2 column to daily passwords table. If there is a value in here, it will show both passwords, so you can manage as you like.

Currently, passwords are cached daily, so I'll show you in person how to clear it.
